### ISSUE TITLE
Error when invoking the save/load menu.

### ISSUE THREAD

**Issue by Mutantovich** [KD-lab-Open-Source/Perimeter#100]
In the latest build, pressing the Save or Load buttons causes the game to crash. 
[perimeter_crash.zip](https://github.com/KD-lab-Open-Source/Perimeter/files/8013972/perimeter_crash.zip)

**Comment by IonAgorria** [comment]
Hello, does this still happen? also please provide logfile.txt after the crash occurred (the path should be at the end of error dialog) as perimeter_crash is used for store saves during crash so doesnt not have much information

**Comment by Mutantovich** [comment]
Hello, it's not happening anymore.

пн, 25 сент. 2023 г. в 20:49, Ion Agorria ***@***.***>:

**Comment by IonAgorria** [comment]
Great, thanks! closing issue
