### ISSUE TITLE
Выравнивание текста версии в главном меню

### ISSUE THREAD

**Issue by DeltaDesignRus** [KD-lab-Open-Source/Perimeter#114]
Текст всегда находится в одном и том же месте. Было бы лучше, что бы он выравнивался по правой стороне экрана
![image](https://user-images.githubusercontent.com/19409260/227220676-d1c12348-225a-4d31-a272-0c55a337fa5a.png)

**Comment by stalkerg** [comment]
Проще тогда по левой границе.
