### ISSUE TITLE
Where to buy the Perimeter?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [KD-lab-Open-Source/Perimeter#127]

**Comment by DeltaDesignRus** [comment]
в Steam

**Comment by IonAgorria** [comment]
There is planned re-release on Steam by K-D Lab association which will use opensource version of code, reworked game assets and other niceties in future:
https://store.steampowered.com/app/2530170/PERIMETER_Legate_Edition/

**Comment by vitaly-zdanevich** [comment]
No Linux support?

**Comment by vitaly-zdanevich** [comment]
Wow, thanks for Linux support!
