### ISSUE TITLE
Change the LOD system landscape settings for high detail

### ISSUE THREAD

**Issue by DeltaDesignRus** [KD-lab-Open-Source/Perimeter#142]
На высокой детализации ландшафта отсутствует LOD, и чанки не упрощаются в зависимости от расстояния. 
Это избыточно, поэтому LOD нужно реализовать для настройки высокой детализации, но сделать его менее агрессивным, чем Medium

**Comment by DeltaDesignRus** [comment]
![Untitled-1](https://github.com/KD-lab-Open-Source/Perimeter/assets/19409260/dffc63df-95fb-4220-80f1-eded7eb1f9c1)
Нужно сделать вот так. Поместить камеру в угол карты, что бы она выглядела, как на моем скриншоте. Что бы примерно на 1/3 карты детализация была максимальной, потом почти вся карта на один уровень менее детализированной, и вдали, где туман, там ещё на один уровень менее детализированной. 
Тогда мы получим достаточно хорошее качество на общих видах, а на близких видах качество будет максимальным!

**Comment by IonAgorria** [comment]
Implemented in 3.1.3
