### ISSUE TITLE
Change selection priority

### ISSUE THREAD

**Issue by DeltaDesignRus** [KD-lab-Open-Source/Perimeter#158]
Изменить приоритет выделения в игре, что бы в первую очередь выделялись Ядра, после них здания, после них ММП, и уже после них сквады.
Нужно, что бы можно было выделяя рамкой выделить несколько нужных ядер, что бы быстро поднимать периметр.
Сквады вызываются либо на панели, либо F1-F2 и т.д., либо точным нажатием на них.

**Comment by DeltaDesignRus** [comment]
![Untitled-1](https://github.com/KD-lab-Open-Source/Perimeter/assets/19409260/4d6e59db-e584-48c7-8f71-4dafb6a0e4f5)
SQUAD>MMP>BUILDINGS>CORES
**CORES>BUILDINGS>MMP>SQUAD**
CORES>SQUAD>BUILDINGS>MMP
etc

**Comment by KBOPYM** [comment]
Was looking for another thing, but this one is defined here.
https://github.com/KD-lab-Open-Source/Perimeter/blob/cmake/Source/UserInterface/SelectManager.cpp#L57

Adding a setting is a different thing.
