### ISSUE TITLE
Предложение: проверка соответствия AttributeLibrary

### ISSUE THREAD

**Issue by AkakiyAndrew** [KD-lab-Open-Source/Perimeter#16]
Перед началом сетевого матча сверять у игроков хэш-сумму файла с атрибутами юнитов ./Scripts/AttributeLibrary, дабы из-за этого не возникала десинхронизация.

**Comment by DeltaDesignRus** [comment]
Предлагаю ещё сохранять этот файл внутрь реплеев, чтобы в будущем, при просмотре реплея, использовались атрибуты из реплея, а не игры

**Comment by Pechkin352** [comment]
Добавить отображение версии AttributeLibrary в главном меню после версии игры (1.02.7, например) тоже было бы неплохо

**Comment by Pechkin352** [comment]
Хорошо бы изменить шаблон имен для автоматически записываемых реплеев с указанием игроков, карты, фракций и тд. Сыграв не один десяток игр становится трудно (-> невозможно) вспомнить где какая. 
![PerimAutosave](https://user-images.githubusercontent.com/60910618/121117276-39121e80-c85b-11eb-9ed5-3480d92385a8.jpg)
