### ISSUE TITLE
Small multiplayer QoL changes

### ISSUE THREAD

**Issue by KBOPYM** [KD-lab-Open-Source/Perimeter#162]
-В режиме сражений есть возможность выживать против скверны, если не выбраны противники. Предлагаю сделать аналогично для мультиплеера, если игроки в одном клане, т.е. нет противников, то задача как можно дольше вместе выжить против скверны.
-Возможность выбрать "Случайную" коалицию для игры (и/или случайный фрейм)

**Comment by DeltaDesignRus** [comment]
Updated existing issue #64 and closing this one
