### ISSUE TITLE
Separate AttributeLibrary between MP and SP

### ISSUE THREAD

**Issue by V1Htor** [KD-lab-Open-Source/Perimeter#167]
For avoiding breaking campaigns with balance changes, i propose adding a way for multiplayer to use its own AttributeLibrary file.

**Comment by IonAgorria** [comment]
Already implemented some time ago, documentation:
https://github.com/KD-lab-Open-Source/Perimeter/blob/cmake/MODDING.eng.md#scripts-dir-and-extending-attributelibrary
