### ISSUE TITLE
Ошибка: "cVisGeneric::ErrorMassage() Cannot load font: ...."

### ISSUE THREAD

**Issue by DeltaDesignRus** [KD-lab-Open-Source/Perimeter#33]
Выставляя ултра-высокое разрешение в игре (например 4к), на некоторых машинах можно наблюдать ошибку, говорящую нам о том, что не были найдены файлы шрифтов. По какой-то причине создавая текстурные атласы шрифтов (растровых), лежащих в папке cache_font, не создаются некоторые файлы, в моем случае это был russian_fonts_aero-100.tga. Стоило создать вручную этот файл, путем копирования наибольшего предыдущего, и переименованием его в russian_fonts_aero-100.tga игра запустилась. Отлавливал события в ProcessMonitor.

Частичное, костыльное решение можно найти в дневниках разработчиков widescreen мода поиском по тексту: "18.09.2020 Найден вариант обхода для запуска игры в 4к разрешении".

https://psy-effects.ru/psychosphere/wiki/index.php/Perimeter_Widescreen#.D0.9B.D0.BE.D0.B3_.D1.80.D0.B0.D0.B7.D1.80.D0.B0.D0.B1.D0.BE.D1.82.D0.BA.D0.B8_.D0.B8_.D0.BF.D0.BB.D0.B0.D0.BD.D1.8B

**Comment by DeltaDesignRus** [comment]
Временное решение:
RESOURCE\LocData\Russian\Fonts\Font.ini и RESOURCE\LocData\English\Fonts\Font.ini 
В этом файле нужно уменьшить размер Menu1 и Menu2 до 32, остальное трогать не нужно.
Размер шрифтов в главном меню становится меньше, но так игра запускается в 4K

**Comment by IonAgorria** [comment]
This issue was solved at above commit, but wasn't auto closed due to cmake branch not being main yet :disappointed:
