### ISSUE TITLE
Предложение: Добавить отображение радиуса атаки при постройке и выборе построенного Супероружия

### ISSUE THREAD

**Issue by Pechkin352** [KD-lab-Open-Source/Perimeter#36]
Добавить отображение радиуса атаки для Супероружия, также, как это происходит для обычных турелей - красной пунктирной окружностью

**Comment by DeltaDesignRus** [comment]
Радиус не влезет в границы экрана же. Такое только со свободной камерой можно будет использовать, отодвинув камеру подальше.

**Comment by Pechkin352** [comment]
тут 2 момента. отображение радиуса нужно/не нужно? как его реализовать? Причина, по которой создано это обсуждение - у игрока нет возможности оценить, до куда "достреливает" СО, пока не построит его и не начнет целиться. А она должна быть. Для построенного СО отображение радиуса пунктиром не проблема - достаточно будет передвинуть камеру без отдаления. Что делать с не построенным? Отображать радиус на миникарте при выборе места строительства или же (костыль) сделать отображение радиуса сразу после того, как начато строительство - в таком случае игрок сможет сразу же поставить процесс на паузу, и оценить, находятся ли в радиусе поражения объекты, которые он собирается уничтожить.

**Comment by AkakiyAndrew** [comment]
Это реализуется, если в AttributeLibrary выставить параметр Супероружия `ShowCircles=true;`, радиусы минимальной и максимальной дальности будут отображаться перед постройкой и после, при клике на здание.
