### ISSUE TITLE
remove embedded stlport

### ISSUE THREAD

**Issue by SSE4** [KD-lab-Open-Source/Perimeter#41]
the project contains an old stlport (XLibs.Net\stl), possible modified
it doesn't compile on modern compilers (e.g. Clang 12 or Visual Studio 2019)
would be nice to remove it from the source tree
NOTE: stlport uses few non-standard extensions, such as `std:slist`

**Comment by IonAgorria** [comment]
This issue can be closed, stlport in XLibs was removed
