### ISSUE TITLE
Изменить все упоминания Завета Императора

### ISSUE THREAD

**Issue by DeltaDesignRus** [KD-lab-Open-Source/Perimeter#45]
Сейчас в исходниках можно встретить различную информацию о версии игры (1.0.0.1, v2.0.0), а так же название игры.

1. Нужно выловить и заменить **все** упоминания Perimeter: Emperor`s Testament просто на Perimeter. 
2. Удалить иконку Per_Add.ico, вместо неё использовать Perim_icon.ico
3. Изменить версию игры. Последняя версия Геометрии войны была 1.0.0.3 (в главном меню игры отображалось v1.0.3). Пусть вопрос о версии остается дискуссионным, а я предлагаю вариант - версия 1.0.0.4 (v1.0.4),

**Comment by mamontov-cpp** [comment]
А чисто из интереса - там есть модели и правила для Завета Императора в исходниках? Или только упоминания?

**Comment by DeltaDesignRus** [comment]
> А чисто из интереса - там есть модели и правила для Завета Императора в исходниках? Или только упоминания?

В составе исходников нет ресурсов игровых. А так в коде много, где упоминается Завет Императора, а так же есть упоминание электро лаборатории.

**Comment by mamontov-cpp** [comment]
@DeltaDesignRus  Надо бы посмотреть, нет ли там кода электролаборатории и юнитов. А то было бы круто по мне иметь, как возвратников-фракцию, так и юниты электролаборатории

**Comment by DeltaDesignRus** [comment]
> @DeltaDesignRus Надо бы посмотреть, нет ли там кода электролаборатории и юнитов. А то было бы круто по мне иметь, как возвратников-фракцию, так и юниты электролаборатории

Или в будущем попытаться объединить ГВ и ЗИ в один общий проект. В меню компании был бы выбор Основная компания и из ЗИ. И мультиплеер с дополнительной фракцией.

**Comment by Aidoneus** [comment]
Поддерживаю объединение. Правда, надо будет доправить (помимо прочего, конечно), чтобы юниты-электро не вытесняли юнитов Возврата + сбалансировать их + сделать правку кода интерфейса, чтобы они все помещались одновременно. Я когда-то правку для своего мода делал, приложил скриншот. Второй вариант (который снизу), наверное, слишком кардинальный (в моде я там доп. функции для сквадов делал, тут они не нужны); а первый (верхний) вполне подошёл бы, думаю.

![squad_tabs](https://user-images.githubusercontent.com/7126889/121798874-d09bb680-cc39-11eb-99a1-aec56f49f395.png)

**Comment by Aidoneus** [comment]
[intf_plus_normal.zip](https://github.com/KranX/Perimeter/files/6643458/intf_plus_normal.zip)
Если кому-то интересно потеребить будет – прикладываю архив с InterfaceAttributes и intf.tga для такой правки интерфейса. Правда, не знаю, что у этого всего с совместимостью с HD/widescreen-патчами, делал ещё в 2013 году или раньше.

**Comment by IonAgorria** [comment]
Considering that code seems to have stuff for both ET new units and harkback still seems to work after uncommenting, I also agree in trying to mix or at least not removing ET stuff, having a way to switch between original and ET ingame sounds like a good idea too. Maybe a third option for a mixed/enhanced game mode? 😝

**Comment by d10sfan** [comment]
For ET, is there a way to play the Emperor's Testament with perimeter? Trying with the built version the menu shows up almost all black, while the original game works fine.

**Comment by IonAgorria** [comment]
I have been working on fixing the support for ET and adding automatic content detection (and a way to pass game content path in cmdline arg instead of using current dir) so this branch should work with both games https://github.com/IonAgorria/Perimeter/tree/custom_res

Also took the @Aidoneus idea of compressing the unit icons and relocating some structure icons, these are injected at runtime after loading interfaceattributes so there is no need to updating it. I still have to implement how to merge 2 game contents without replacing certains files such as mission files, translations and harkback models.
![Screenshot_20210921_224822](https://user-images.githubusercontent.com/1096830/134245485-a4b95433-90d8-4a69-ba7e-615894c677db.png)


I plan on making a PR once I test it a bit more
