### ISSUE TITLE
Убрать поддежку Bink Video (*.bik) видео, и добавить что-то современное, открытое

### ISSUE THREAD

**Issue by DeltaDesignRus** [KD-lab-Open-Source/Perimeter#48]
Сейчас в игре используется библиотека binkw32.dll (”Bink Video” video codec for games, developed by RAD Game Tools, Inc.).
Предлагаю выкинуть её, а на его место поставить что-то открытое и современное. Чтобы была возможность использовать видео с распространенными кодеками и форматами.

**Comment by Teashrock** [comment]
Зачем выкидывать? Почему бы просто не встроить поддержку новых форматов?

**Comment by IonAgorria** [comment]
Video Player for .bik files using FFmpeg has been added, and it should support other video/audio formats if FFmpeg is compiled with the support.
