### ISSUE TITLE
ogg audio playback

### ISSUE THREAD

**Issue by SSE4** [KD-lab-Open-Source/Perimeter#50]
there is a `playogg` library we don't have any sources for.
it's used to play ogg/vorbis music files.
we have to replace it with our own cross-platform implementation.
it could be based on open-source, free of charge solutions:
- [ffmpeg](https://www.ffmpeg.org/)
- [gstreamer](https://gstreamer.freedesktop.org/)
- [SDL_mixer](https://www.libsdl.org/projects/SDL_mixer/)
- plain usage of [libogg](https://xiph.org/ogg/) and [libvorbis](https://xiph.org/vorbis/)

**Comment by stalkerg** [comment]
If you not needed FX like pitch the SDL2_Mixer will be the best. 
Vangers was moved from Mixer to Clunk because we have some specific requirements.

**Comment by IonAgorria** [comment]
Small update, the sources for PlayOgg was found and is already part of builds (it uses libogg/libvorbis and dsound) so maybe issue title/desc can be changed?

In future it would be necessary to drop directX sound dependency and use a more portable alternative such as SDL2...
