### ISSUE TITLE
Add extra info for addons/mods

### ISSUE THREAD

**Issue by IonAgorria** [KD-lab-Open-Source/Perimeter#82]
Currently addons (soon renamed to mods) don't have any sort of info relating to itself, since game has .ini support an example ini format for mod.ini may be something like:

[Mod]
name=My mod - Mandatory, name to display in mod list and acts as identifier
version=1.0.0 - Version of mod
description=Example mod description - Optional description for mod
authors=AuthorA, AuthorB - List of authors separated by comma
url=URL - Optional url for mod

[Content]
priority=0 - Order of loading, higher ones are loaded last and they take effect
required_content=PERIMETER|PERIMETER_ET - List of required contents need to be present to allow this mod to be loaded
disallowed_content=PERIMETER|PERIMETER_ET - Optional: List of contents which this mod is not compatible with
required_mods=OtherModName, AnotherMod - Optional: List of mods required to be loaded to allow this mod to be loaded, separated by comma
campaign_disallowed=false - Optional: tells game to not load this mod when playing a campaign (this would require reloading game if there is a mod with this option set)

**Comment by XxBigManxX** [comment]
It would also be nice to have a window pop up when selecting a mod (like when viewing a map in a lobby) and that window can display the mod description.
